#!/bin/bash

function fail() {
  echo $1
  echo "example usage:"
  echo
  echo -e "\t$ ${0##*/} \"hello, world\""
  echo -e "\t$ ${0##*/} # uses content in clipboard"
  echo
  exit 1
}

if [ $# -eq 0 ]; then
  TWEET=`pbpaste`
  echo -e "No argument supplied, checking clipboard:\n"
  echo -e "\t$TWEET"
  echo
elif [ $# -gt 1 ]; then
  fail "whoa, that's too many arguments."
else
  TWEET=$1
fi

if [ -z "$TWEET" ]; then
  fail "argh... either an empty argument or nothing in the clipboard to check!"
fi

COUNT=${#TWEET}
DIFF=$((140 - $COUNT))

if [ $COUNT -le "140" ]; then
  echo "Tweet away! ($DIFF characters remaining)"
else
  echo "Shucks, that's $(($DIFF * -1)) characters too long."
fi
